version: '3.8'
services:
  config-server:
    image: cleverjohann/microservice-config:latest
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=git  # Usar el perfil git para obtener las configuraciones desde el repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: cleverjohann/microservice-eureka:latest
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888  # Importar configuración desde el Config Server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  producto-categoria-service:
    image: cleverjohann/microservice-producto-categoria:latest
    ports:
      - "8040:8040"  # Mapea el puerto fijo 8040 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  correo-service:
    image: schulzc/microservice-correo:1
    ports:
      - "9031:9031"  # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9031/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  usuario-service:
    image: schulzc/microservice-usuario:1
    ports:
      - "9030:9030"  # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9030/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: schulzc/microservice-auth:3
    ports:
      - "9032:9032"  # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - correo-service
      - usuario-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9032/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  carrito-service:
    image: schulzc/microservice-carrito:9
    ports:
      - "9033:9033"  # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - usuario-service
      - producto-categoria-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9033/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  reserva-inventario-service:
    image: cleverjohann/microservice-reserva-inventario:latest
    ports:
      - "8041:8041"  # Mapea el puerto fijo 8040 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8041/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pedido-service:
    image: schulzc/microservice-pedido:15
    ports:
      - "9034:9034"  # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - usuario-service
      - carrito-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9034/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5