version: "3.8"
services:
  config-server:
    image: schulzc/microservice-config:2
    ports:
      - "8888:8888"
    environment:
      - SPRING_PROFILES_ACTIVE=git # Usar el perfil git para obtener las configuraciones desde el repo
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  eureka-server:
    image: schulzc/microservice-gateway:1
    ports:
      - "8761:8761"
    depends_on:
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888 # Importar configuración desde el Config Server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  gateway-service:
    image: schulzc/microservice-gateway:3 # Reemplaza con la etiqueta correcta si es necesario
    ports:
      - "8080:8080" # Mapea el puerto 8080 del contenedor al puerto 8080 del host
    depends_on:
      - config-server
      - eureka-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  producto-categoria-service:
    image: cleverjohann/microservice-producto-categoria:latest
    ports:
      - "8040:8040" # Mapea el puerto fijo 8040 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8040/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  correo-service:
    image: schulzc/microservice-correo:1
    ports:
      - "9031:9031" # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9031/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  usuario-service:
    image: schulzc/microservice-usuario:1
    ports:
      - "9030:9030" # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9030/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  auth-service:
    image: schulzc/microservice-auth:9
    ports:
      - "9032:9032" # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - correo-service
      - usuario-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9032/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  carrito-service:
    image: schulzc/microservice-carrito:9
    ports:
      - "9033:9033" # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - usuario-service
      - producto-categoria-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9033/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  reserva-inventario-service:
    image: cleverjohann/microservice-reserva-inventario:latest
    ports:
      - "8041:8041" # Mapea el puerto fijo 8041 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8041/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  pedido-service:
    image: schulzc/microservice-pedido:23
    ports:
      - "9034:9034" # Mapea el puerto fijo 8050 del contenedor al host
    depends_on:
      - eureka-server
      - config-server
      - usuario-service
      - carrito-service
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9034/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice-pagos:
    build: .
    image: cleverjohann/microservice-pagos:latest
    ports:
      - "8044:8044"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8050/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  microservice-envios:
    build: .
    image: cleverjohann/microservice-envios:latest
    ports:
      - "8045:8045"
    depends_on:
      - eureka-server
      - config-server
    environment:
      - SPRING_CONFIG_IMPORT=optional:configserver:http://config-server:8888
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8045/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
