server:
  port: 8080

spring:
  application:
    name: msvc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: productos
          uri: http://localhost:4030
          predicates:
            - Path=/api/productos/**
        - id: categorias
          uri: http://localhost:8042
          predicates:
            - Path=/api/categorias/**
        - id: usuarios
          uri: http://localhost:9030
          predicates:
            - Path=/api/Usuario/**
        - id: auth
          uri: http://localhost:9032
          predicates:
            - Path=/auth/**
        - id: correo
          uri: http://localhost:9031
          predicates:
           - Path=/enviar-correo/**
eureka:
  client:
    register-with-eureka: false