apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: config-server
  template:
    metadata:
      labels:
        app: config-server
    spec:
      containers:
        - name: config-server
          image: cleverjohann/microservice-config:latest  # Usa la imagen de Docker Hub que subiste
          ports:
            - containerPort: 8888  # El puerto en el contenedor donde el servicio está corriendo
---
apiVersion: v1
kind: Service
metadata:
  name: config-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8888  # Puerto expuesto
      targetPort: 8888  # Puerto en el contenedor
  selector:
    app: config-server
