apiVersion: apps/v1
kind: Deployment
metadata:
  name: eureka-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eureka-server
  template:
    metadata:
      labels:
        app: eureka-server
    spec:
      containers:
        - name: eureka-server
          image: cleverjohann/microservice-eureka:latest  # Usa la imagen de Docker Hub que subiste
          ports:
            - containerPort: 8761  # El puerto en el contenedor donde el servicio está corriendo
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8761  # Puerto expuesto
      targetPort: 8761  # Puerto en el contenedor
  selector:
    app: eureka-server
