apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-server
  template:
    metadata:
      labels:
        app: gateway-server
    spec:
      containers:
        - name: gateway-server
          image: cleverjohann/microservice-gateway:latest  # Usa la imagen de Docker Hub que subiste
          ports:
            - containerPort: 8080  # El puerto en el contenedor donde el servicio está corriendo
---
apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080  # Puerto expuesto
      targetPort: 8080  # Puerto en el contenedor
  selector:
    app: gateway-server
