server:
  port: 8080

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: msvc-gateway
  cloud:
    gateway:
      routes:
        - id: productos
          uri: http://localhost:8040
          predicates:
            - Path=/api/productos/**
        - id: categorias
          uri: http://localhost:8040
          predicates:
            - Path=/api/categorias/**
        - id: correo
          uri: http://localhost:9031
          predicates:
            - Path=/enviar-correo/**
        - id: usuario
          uri: http://localhost:9030
          predicates:
            - Path=/api/usuarios/**
        - id: auth
          uri: http://localhost:9032
          predicates:
            - Path=/auth/**
        - id: carrito
          uri: http://localhost:9033
          predicates:
            - Path=/api/carrito/**
        - id: reserva-inventario
          uri: http://localhost:8041
          predicates:
            - Path=/api/inventario/**
        - id: pedido
          uri: http://localhost:9034
          predicates:
            - Path=/api/pedido/**
        - id: pagos
          uri: http://localhost:8044
          predicates:
            - Path=/api/pagos/**
        - id: envios
          uri: http://localhost:8045
          predicates:
            - Path=/api/envios/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
